# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protos.messages_pb2 as messages__pb2


class BroadcastStub(object):
    """Server------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendRequest = channel.unary_unary(
                '/grpc.Broadcast/SendRequest',
                request_serializer=messages__pb2.Request.SerializeToString,
                response_deserializer=messages__pb2.Empty.FromString,
                )
        self.SubRequest = channel.unary_stream(
                '/grpc.Broadcast/SubRequest',
                request_serializer=messages__pb2.Empty.SerializeToString,
                response_deserializer=messages__pb2.Request.FromString,
                )
        self.SendResponse = channel.unary_unary(
                '/grpc.Broadcast/SendResponse',
                request_serializer=messages__pb2.Response.SerializeToString,
                response_deserializer=messages__pb2.Empty.FromString,
                )
        self.SubResponse = channel.unary_stream(
                '/grpc.Broadcast/SubResponse',
                request_serializer=messages__pb2.Empty.SerializeToString,
                response_deserializer=messages__pb2.Response.FromString,
                )
        self.SendAction = channel.unary_unary(
                '/grpc.Broadcast/SendAction',
                request_serializer=messages__pb2.Action.SerializeToString,
                response_deserializer=messages__pb2.Empty.FromString,
                )
        self.SubAction = channel.unary_stream(
                '/grpc.Broadcast/SubAction',
                request_serializer=messages__pb2.Empty.SerializeToString,
                response_deserializer=messages__pb2.Action.FromString,
                )
        self.SendWarning = channel.unary_unary(
                '/grpc.Broadcast/SendWarning',
                request_serializer=messages__pb2.Warning.SerializeToString,
                response_deserializer=messages__pb2.Empty.FromString,
                )
        self.SubWarning = channel.unary_stream(
                '/grpc.Broadcast/SubWarning',
                request_serializer=messages__pb2.Empty.SerializeToString,
                response_deserializer=messages__pb2.Warning.FromString,
                )
        self.SendError = channel.unary_unary(
                '/grpc.Broadcast/SendError',
                request_serializer=messages__pb2.Error.SerializeToString,
                response_deserializer=messages__pb2.Empty.FromString,
                )
        self.SubError = channel.unary_stream(
                '/grpc.Broadcast/SubError',
                request_serializer=messages__pb2.Empty.SerializeToString,
                response_deserializer=messages__pb2.Error.FromString,
                )


class BroadcastServicer(object):
    """Server------------------------------------------------------------------------

    """

    def SendRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendWarning(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubWarning(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendError(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubError(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BroadcastServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.SendRequest,
                    request_deserializer=messages__pb2.Request.FromString,
                    response_serializer=messages__pb2.Empty.SerializeToString,
            ),
            'SubRequest': grpc.unary_stream_rpc_method_handler(
                    servicer.SubRequest,
                    request_deserializer=messages__pb2.Empty.FromString,
                    response_serializer=messages__pb2.Request.SerializeToString,
            ),
            'SendResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.SendResponse,
                    request_deserializer=messages__pb2.Response.FromString,
                    response_serializer=messages__pb2.Empty.SerializeToString,
            ),
            'SubResponse': grpc.unary_stream_rpc_method_handler(
                    servicer.SubResponse,
                    request_deserializer=messages__pb2.Empty.FromString,
                    response_serializer=messages__pb2.Response.SerializeToString,
            ),
            'SendAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAction,
                    request_deserializer=messages__pb2.Action.FromString,
                    response_serializer=messages__pb2.Empty.SerializeToString,
            ),
            'SubAction': grpc.unary_stream_rpc_method_handler(
                    servicer.SubAction,
                    request_deserializer=messages__pb2.Empty.FromString,
                    response_serializer=messages__pb2.Action.SerializeToString,
            ),
            'SendWarning': grpc.unary_unary_rpc_method_handler(
                    servicer.SendWarning,
                    request_deserializer=messages__pb2.Warning.FromString,
                    response_serializer=messages__pb2.Empty.SerializeToString,
            ),
            'SubWarning': grpc.unary_stream_rpc_method_handler(
                    servicer.SubWarning,
                    request_deserializer=messages__pb2.Empty.FromString,
                    response_serializer=messages__pb2.Warning.SerializeToString,
            ),
            'SendError': grpc.unary_unary_rpc_method_handler(
                    servicer.SendError,
                    request_deserializer=messages__pb2.Error.FromString,
                    response_serializer=messages__pb2.Empty.SerializeToString,
            ),
            'SubError': grpc.unary_stream_rpc_method_handler(
                    servicer.SubError,
                    request_deserializer=messages__pb2.Empty.FromString,
                    response_serializer=messages__pb2.Error.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.Broadcast', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Broadcast(object):
    """Server------------------------------------------------------------------------

    """

    @staticmethod
    def SendRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.Broadcast/SendRequest',
            messages__pb2.Request.SerializeToString,
            messages__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.Broadcast/SubRequest',
            messages__pb2.Empty.SerializeToString,
            messages__pb2.Request.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.Broadcast/SendResponse',
            messages__pb2.Response.SerializeToString,
            messages__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.Broadcast/SubResponse',
            messages__pb2.Empty.SerializeToString,
            messages__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.Broadcast/SendAction',
            messages__pb2.Action.SerializeToString,
            messages__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.Broadcast/SubAction',
            messages__pb2.Empty.SerializeToString,
            messages__pb2.Action.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendWarning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.Broadcast/SendWarning',
            messages__pb2.Warning.SerializeToString,
            messages__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubWarning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.Broadcast/SubWarning',
            messages__pb2.Empty.SerializeToString,
            messages__pb2.Warning.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendError(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.Broadcast/SendError',
            messages__pb2.Error.SerializeToString,
            messages__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubError(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.Broadcast/SubError',
            messages__pb2.Empty.SerializeToString,
            messages__pb2.Error.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
