# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='communication',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0emessages.proto\x12\rcommunication\"\x10\n\x0eRequestVoltage\"\x10\n\x0eRequestCurrent\"\x14\n\x12RequestTemperature\"m\n\x06\x41\x63tion\x12:\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32 .communication.Action.ActionType:\x08TURN_OFF\"\'\n\nActionType\x12\x0c\n\x08TURN_OFF\x10\x01\x12\x0b\n\x07TURN_ON\x10\x02\"\x1f\n\x0fResponseVoltage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x05\"\x1f\n\x0fResponseCurrent\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x05\"#\n\x13ResponseTemperature\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x05\"\x1a\n\x07Warning\x12\x0f\n\x07message\x18\x01 \x02(\t\"\x18\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x02(\t'
)



_ACTION_ACTIONTYPE = _descriptor.EnumDescriptor(
  name='ActionType',
  full_name='communication.Action.ActionType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TURN_OFF', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TURN_ON', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=161,
  serialized_end=200,
)
_sym_db.RegisterEnumDescriptor(_ACTION_ACTIONTYPE)


_REQUESTVOLTAGE = _descriptor.Descriptor(
  name='RequestVoltage',
  full_name='communication.RequestVoltage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=49,
)


_REQUESTCURRENT = _descriptor.Descriptor(
  name='RequestCurrent',
  full_name='communication.RequestCurrent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=67,
)


_REQUESTTEMPERATURE = _descriptor.Descriptor(
  name='RequestTemperature',
  full_name='communication.RequestTemperature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=89,
)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='communication.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='communication.Action.action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ACTION_ACTIONTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=200,
)


_RESPONSEVOLTAGE = _descriptor.Descriptor(
  name='ResponseVoltage',
  full_name='communication.ResponseVoltage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='communication.ResponseVoltage.data', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=233,
)


_RESPONSECURRENT = _descriptor.Descriptor(
  name='ResponseCurrent',
  full_name='communication.ResponseCurrent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='communication.ResponseCurrent.data', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=266,
)


_RESPONSETEMPERATURE = _descriptor.Descriptor(
  name='ResponseTemperature',
  full_name='communication.ResponseTemperature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='communication.ResponseTemperature.data', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=303,
)


_WARNING = _descriptor.Descriptor(
  name='Warning',
  full_name='communication.Warning',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='communication.Warning.message', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=331,
)


_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='communication.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='communication.Error.message', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=357,
)

_ACTION.fields_by_name['action'].enum_type = _ACTION_ACTIONTYPE
_ACTION_ACTIONTYPE.containing_type = _ACTION
DESCRIPTOR.message_types_by_name['RequestVoltage'] = _REQUESTVOLTAGE
DESCRIPTOR.message_types_by_name['RequestCurrent'] = _REQUESTCURRENT
DESCRIPTOR.message_types_by_name['RequestTemperature'] = _REQUESTTEMPERATURE
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
DESCRIPTOR.message_types_by_name['ResponseVoltage'] = _RESPONSEVOLTAGE
DESCRIPTOR.message_types_by_name['ResponseCurrent'] = _RESPONSECURRENT
DESCRIPTOR.message_types_by_name['ResponseTemperature'] = _RESPONSETEMPERATURE
DESCRIPTOR.message_types_by_name['Warning'] = _WARNING
DESCRIPTOR.message_types_by_name['Error'] = _ERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestVoltage = _reflection.GeneratedProtocolMessageType('RequestVoltage', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTVOLTAGE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:communication.RequestVoltage)
  })
_sym_db.RegisterMessage(RequestVoltage)

RequestCurrent = _reflection.GeneratedProtocolMessageType('RequestCurrent', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTCURRENT,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:communication.RequestCurrent)
  })
_sym_db.RegisterMessage(RequestCurrent)

RequestTemperature = _reflection.GeneratedProtocolMessageType('RequestTemperature', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTTEMPERATURE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:communication.RequestTemperature)
  })
_sym_db.RegisterMessage(RequestTemperature)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:communication.Action)
  })
_sym_db.RegisterMessage(Action)

ResponseVoltage = _reflection.GeneratedProtocolMessageType('ResponseVoltage', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEVOLTAGE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:communication.ResponseVoltage)
  })
_sym_db.RegisterMessage(ResponseVoltage)

ResponseCurrent = _reflection.GeneratedProtocolMessageType('ResponseCurrent', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSECURRENT,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:communication.ResponseCurrent)
  })
_sym_db.RegisterMessage(ResponseCurrent)

ResponseTemperature = _reflection.GeneratedProtocolMessageType('ResponseTemperature', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSETEMPERATURE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:communication.ResponseTemperature)
  })
_sym_db.RegisterMessage(ResponseTemperature)

Warning = _reflection.GeneratedProtocolMessageType('Warning', (_message.Message,), {
  'DESCRIPTOR' : _WARNING,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:communication.Warning)
  })
_sym_db.RegisterMessage(Warning)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
  'DESCRIPTOR' : _ERROR,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:communication.Error)
  })
_sym_db.RegisterMessage(Error)


# @@protoc_insertion_point(module_scope)
