name: Documentation
on:
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Documentation
      uses: eagletrt/documentation@main
      with:
        author: Eagletrt           # project author
        project: Handcart          # project name
        rootfile: Title            # project title
        folders: ../backend/main.py          # path of folders and files you want to document
        version: 1.0.0             # project version
        release: 1.0.0             # project release
        language: python           # language used
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        nojekyll: true 
        branch: docs # The branch the action should deploy to.
        folder: docs/_build # The folder the action should deploy.
